version: '3.8'

services:
  django:
    build: ./django
    command: uvicorn geodjango.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    volumes:
      - ./src:/code
    depends_on:
      - db
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    depends_on:
      - django
volumes:
  postgres-data:
